--data aggregation from the Last Paid Click attribution model

WITH PAID_CLICK AS (
    SELECT
        S.VISITOR_ID,
        VISIT_DATE,
        SOURCE AS UTM_SOURCE,
        MEDIUM AS UTM_MEDIUM,
        CAMPAIGN AS UTM_CAMPAIGN,
        LEAD_ID,
        CREATED_AT,
        AMOUNT,
        CLOSING_REASON,
        STATUS_ID,
        CASE
            WHEN CLOSING_REASON = 'Успешная продажа' OR STATUS_ID = 142
                THEN 1
            ELSE 0
        END AS PURCHASES,
        ROW_NUMBER()
            OVER (PARTITION BY S.VISITOR_ID ORDER BY VISIT_DATE DESC)
        AS RN
    FROM SESSIONS AS S
    LEFT JOIN LEADS AS L
        ON
            S.VISITOR_ID = L.VISITOR_ID
            AND VISIT_DATE <= CREATED_AT
    WHERE MEDIUM != 'organic'
),

LAST_PAID_CLICK AS (
    SELECT
        *,
        DATE_TRUNC('day', VISIT_DATE) AS DAY_VISIT_DATE
    FROM PAID_CLICK
    WHERE RN = 1
    ORDER BY
        AMOUNT DESC NULLS LAST,
        VISIT_DATE ASC,
        UTM_SOURCE ASC,
        UTM_MEDIUM ASC,
        UTM_CAMPAIGN ASC
),

VK_DAILY AS (
    SELECT
        UTM_SOURCE,
        UTM_MEDIUM,
        UTM_CAMPAIGN,
        DATE_TRUNC('day', CAMPAIGN_DATE) AS VK_CAMPAIGN_DATE,
        SUM(DAILY_SPENT) AS TOTAL_VK_SPENT
    FROM VK_ADS
    GROUP BY
        DATE_TRUNC('day', CAMPAIGN_DATE), UTM_SOURCE, UTM_MEDIUM, UTM_CAMPAIGN
),

YA_DAILY AS (
    SELECT
        UTM_SOURCE,
        UTM_MEDIUM,
        UTM_CAMPAIGN,
        DATE_TRUNC('day', CAMPAIGN_DATE) AS YA_CAMPAIGN_DATE,
        SUM(DAILY_SPENT) AS TOTAL_YA_SPENT
    FROM YA_ADS
    GROUP BY
        DATE_TRUNC('day', CAMPAIGN_DATE), UTM_SOURCE, UTM_MEDIUM, UTM_CAMPAIGN
),

LEADS_AGR AS (
    SELECT
        DAY_VISIT_DATE AS VISIT_DATE,
        LPC.UTM_SOURCE,
        LPC.UTM_MEDIUM,
        LPC.UTM_CAMPAIGN,
        COUNT(VISITOR_ID) AS VISITORS_COUNT,
        COUNT(LEAD_ID) AS LEADS_COUNT,
        SUM(PURCHASES) AS PURCHASES_COUNT,
        SUM(COALESCE(AMOUNT, 0)) AS REVENUE
    FROM LAST_PAID_CLICK AS LPC
    GROUP BY DAY_VISIT_DATE, LPC.UTM_SOURCE, LPC.UTM_MEDIUM, LPC.UTM_CAMPAIGN
)
--table cost_revenue
SELECT
    TO_CHAR(VISIT_DATE, 'YYYY-MM-DD') AS VISIT_DATE,
    VISITORS_COUNT,
    L.UTM_SOURCE,
    L.UTM_MEDIUM,
    L.UTM_CAMPAIGN,
    COALESCE(TOTAL_YA_SPENT,TOTAL_VK_SPENT) AS TOTAL_COST,
    LEADS_COUNT,
    PURCHASES_COUNT,
    REVENUE
FROM LEADS_AGR AS L
LEFT JOIN VK_DAILY AS VK
    ON
        L.VISIT_DATE = VK.VK_CAMPAIGN_DATE
        AND L.UTM_SOURCE = VK.UTM_SOURCE
        AND L.UTM_MEDIUM = VK.UTM_MEDIUM
        AND L.UTM_CAMPAIGN = VK.UTM_CAMPAIGN
LEFT JOIN YA_DAILY AS YA
    ON
        L.VISIT_DATE = YA.YA_CAMPAIGN_DATE
        AND L.UTM_SOURCE = YA.UTM_SOURCE
        AND L.UTM_MEDIUM = YA.UTM_MEDIUM
        AND L.UTM_CAMPAIGN = YA.UTM_CAMPAIGN
ORDER BY
    REVENUE DESC NULLS LAST, VISIT_DATE ASC, VISITORS_COUNT DESC, L.UTM_SOURCE ASC, L.UTM_MEDIUM ASC, L.UTM_CAMPAIGN ASC
--LIMIT 15
;
