--Datamart for the Last Paid Click attribution model with ROW_NUMBER
WITH LAST_PAID_CLICK AS (
    SELECT
        S.VISITOR_ID,
        VISIT_DATE,
        SOURCE AS UTM_SOURCE,
        MEDIUM AS UTM_MEDIUM,
        CAMPAIGN AS UTM_CAMPAIGN,
        LEAD_ID,
        CREATED_AT,
        AMOUNT,
        CLOSING_REASON,
        STATUS_ID,
        ROW_NUMBER()
            OVER (PARTITION BY S.VISITOR_ID ORDER BY VISIT_DATE DESC)
        AS RN
    FROM SESSIONS AS S
    LEFT JOIN LEADS AS L
        ON S.VISITOR_ID = L.VISITOR_ID
    WHERE MEDIUM != 'organic'
)

SELECT
    VISITOR_ID,
    VISIT_DATE,
    UTM_SOURCE,
    UTM_MEDIUM,
    UTM_CAMPAIGN,
    LEAD_ID,
    CREATED_AT,
    AMOUNT,
    CLOSING_REASON,
    STATUS_ID
FROM LAST_PAID_CLICK
WHERE RN = 1
ORDER BY
    AMOUNT DESC NULLS LAST,
    VISIT_DATE ASC,
    UTM_SOURCE ASC,
    UTM_MEDIUM ASC,
    UTM_CAMPAIGN ASC
LIMIT 10
